version: '3.7'

services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - 'db:db'
    depends_on:
      - db
    environment:
      HISTFILE: /usr/src/app/log/.bash_history 
      DB_HOST: db
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
